server:
  port: 8089
spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/OshandaB/microservice-config.git
          default-label: main
          clone-on-start: true
          username: OshandaB
          password: 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
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/